"""first  migration

Revision ID: 33a70a46942c
Revises: 
Create Date: 2025-07-18 11:06:24.844079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a70a46942c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.Column('measure_type', sa.Enum('WEIGHT', 'VOLUME', 'LENGTH', name='measuretype'), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('url_image', sa.String(length=255), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_branch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_store', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_store'], ['store.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_store_branch', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.CheckConstraint('start_date <= expiration', name='ck_offer_date_order'),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_store_branch'], ['store_branch.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    op.drop_table('store_branch')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('category')
    # ### end Alembic commands ###
