"""third  migration

Revision ID: 620b738db2af
Revises: b3404e58c3e4
Create Date: 2025-07-24 22:36:54.060781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620b738db2af'
down_revision: Union[str, Sequence[str], None] = 'b3404e58c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_branch', sa.Column('address', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_branch', 'address')
    # ### end Alembic commands ###
