"""second migration

Revision ID: c71e9c1ffbd5
Revises: 8c9f38fab82f
Create Date: 2025-07-14 12:46:05.071415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71e9c1ffbd5'
down_revision: Union[str, Sequence[str], None] = '8c9f38fab82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'previous_price')
    op.add_column('product', sa.Column('url_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'url_image')
    op.add_column('offer', sa.Column('previous_price', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
