"""Third Migration

Revision ID: e5e55e5a1e45
Revises: 1576397a0bc1
Create Date: 2025-07-10 21:39:44.661468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5e55e5a1e45'
down_revision: Union[str, Sequence[str], None] = '1576397a0bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url_icon', sa.String(length=255), nullable=True))
    op.drop_column('category', 'urlIcon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('urlIcon', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('category', 'url_icon')
    # ### end Alembic commands ###
