"""Second Migration

Revision ID: ec7dcbc96466
Revises: e2872409b94e
Create Date: 2025-07-07 16:20:21.969962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec7dcbc96466'
down_revision: Union[str, Sequence[str], None] = 'e2872409b94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('expiration', sa.String(length=10), nullable=False))
    op.drop_column('offer', 'expiration_offer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('expiration_offer', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('offer', 'expiration')
    # ### end Alembic commands ###
